Vagrant.require_version '>= 1.6.0'

# Configuration settings for the Virtual Machine.
$update_channel = 'beta'
$image_version = 'current'
$vm_memory = 1024
$vm_cpus = 1
$forwarded_ports = {
  '80' => '8080',
  '443' => '8081'
}
$vm_host = 'core-01'
$vm_ip = '172.17.8.101'

Vagrant.configure('2') do |config|
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  config.vm.box = 'coreos-%s' % [$update_channel]
  if $image_version != 'current'
      config.vm.box_version = $image_version
  end
  config.vm.box_url = 'http://%s.release.core-os.net/amd64-usr/%s/coreos_production_vagrant.json' % [$update_channel, $image_version]

  ['vmware_fusion', 'vmware_workstation'].each do |vmware|
    config.vm.provider vmware do |v, override|
      override.vm.box_url = 'http://%s.release.core-os.net/amd64-usr/%s/coreos_production_vagrant_vmware_fusion.json' % [$update_channel, $image_version]
    end
  end

  config.vm.provider :virtualbox do |v|
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end

  if Vagrant.has_plugin?('vagrant-vbguest') then
    config.vbguest.auto_update = false
  end

  config.vm.define vm_name = $vm_host do |config|
    config.vm.hostname = vm_name

    config.vm.network :private_network, ip: $vm_ip

    $forwarded_ports.each do |guest, host|
      config.vm.network 'forwarded_port', guest: guest, host: host, auto_correct: true
    end

    ['vmware_fusion', 'vmware_workstation'].each do |vmware|
      config.vm.provider vmware do |v|
        v.gui = false
        v.vmx['memsize'] = $vm_memory
        v.vmx['numvcpus'] = $vm_cpus
      end
    end

    config.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.memory = $vm_memory
      vb.cpus = $vm_cpus
    end

    # Create bare git repos.
    config.vm.provision 'shell',
                        inline: 'sudo mkdir -p /var/git/nginx.git /var/git/nginx /var/git/rediscounter.git /var/git/rediscounter'

    config.vm.provision 'shell',
                        inline: 'sudo su && cd /var/git/nginx.git && git --bare init && chown -R core:core /var/git/nginx.git && chown -R core:core /var/git/nginx'

    config.vm.provision 'shell',
                        inline: 'sudo su && cd /var/git/rediscounter.git && git --bare init && chown -R core:core /var/git/rediscounter.git && chown -R core:core /var/git/rediscounter'


    # Copy files into the VM instance upon provision.
    config.vm.provision 'file', source: '../deploy/nginx/certs',
                                destination: '/tmp'

    config.vm.provision 'file', source: '../deploy/units',
                                destination: '/tmp'

    config.vm.provision 'file', source: '../deploy/git/post-receive',
                                destination: '/tmp'

    # Move the files with sudo into the correct remote location.
    config.vm.provision 'shell',
                        inline: 'sudo mv /tmp/certs/rediscounter.crt /etc/ssl/certs'

    config.vm.provision 'shell',
                        inline: 'sudo mv /tmp/certs/rediscounter.key /etc/ssl/private'

    config.vm.provision 'shell',
                        inline: 'sudo mv /tmp/certs/dhparam.pem /etc/ssl/private'

    config.vm.provision 'shell',
                        inline: 'sudo mv /tmp/units/redis.service /etc/systemd/system'

    config.vm.provision 'shell',
                        inline: 'sudo mv /tmp/units/nginx.service /etc/systemd/system'

    config.vm.provision 'shell',
                        inline: 'sudo mv /tmp/units/rediscounter.service /etc/systemd/system'

    config.vm.provision 'shell',
                        inline: 'mv /tmp/post-receive/nginx /var/git/nginx.git/hooks/post-receive'

    config.vm.provision 'shell',
                        inline: 'mv /tmp/post-receive/rediscounter /var/git/rediscounter.git/hooks/post-receive'

    # Set proper permissions.
    config.vm.provision 'shell',
                        inline: 'chmod +x /var/git/nginx.git/hooks/post-receive /var/git/rediscounter.git/hooks/post-receive'


    # Pull in any Docker images we need.
    config.vm.provision 'shell',
                        inline: 'docker pull redis:2.8.21'

    # Enable and start Redis through systemd, this ensures it loads on bootup.
    config.vm.provision 'shell',
                        inline: 'sudo systemctl enable redis.service && sudo systemctl start redis.service'

    # **************************************************************************
    # A few commands need to be ran on your `workstation` before proceeding.
    # --------------------------------------------------------------------------
    # Consult with Chapter 8 of the book to see the details.
    # **************************************************************************

    # **************************************************************************
    # A few commands need to be ran on the `CoreOS host` before proceeding.
    # --------------------------------------------------------------------------
    # Consult with Chapter 8 of the book to see the details.
    # **************************************************************************
  end
end
